export enum OrderStatus{
    NEW="NEW",
    WAITING_CONFIRMATION_SUPPLY="WAITING_CONFIRMATION_SUPPLY",
    CONFIRMED_SUPPLY="CONFIRMED_SUPPLY",
    DENIED_SUPPLY="DENIED_SUPPLY",
    WAITING_PAYMENT="WAITING_PAYMENT",
    APPROVED_PAYMENT="APPROVED_PAYMENT",
    REJECTED_PAYMENT="REJECTED_PAYMENT",
    WAITING_CONFIRMATION_SHIPPING="WAITING_CONFIRMATION_SHIPPING",
    APPROVED_SHIPPING="SHIPPED",
    DELIVERED="DELIVERED"

}